export const APP_PADDING = '30px';

export const ETSY_FEE_PERCENT = 0.065;
export const ETSY_PAYMENT_PROCESSING_FEE_PERCENT = 0.04;
export const ETSY_REGULATORY_OPERATING_FEE_PERCENT = 0.0115;
export const ETSY_ADS_MARKUP_PERCENT = 0.15;
export const ETSY_TAX_RATE_PERCENT = 1.13;
export const ETSY_FLAT_FEE = 0.25;
